<a href="https://colab.research.google.com/github/pranay8297/deep-learning-projects/blob/master/imbue_coding_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
field = [
 "*#..#",
 ".#*#.",
 "*...*"]

In [ ]:
def get_checkpoint_idxs(fields):
    checkpoint_idxs = []
    for idx, row in enumerate(field):
        for cidx, point in enumerate(row):
            if point == '*': checkpoint_idxs.append((idx, cidx))
    return np.array(checkpoint_idxs)

def get_all_combinations(checkpoints, k):
    def solve(l,n,r,index,temp,i,ans):
        if index==r:
            ans.append(temp.copy())
            return temp
        if i>=n:
            return
        temp[index]=l[i]
        solve(l,n,r,index+1,temp,i+1,ans)
        solve(l,n,r,index,temp,i+1,ans)
        return ans

    n = len(checkpoints)
    l=[i for i in range(0,n)]
    q=solve(l,n,k,0,[0]*k,0,[])
    return [tuple(checkpoints[i]) for i in q]

class Node():

    def __init__(self, parent = None, position = None):
        self.parent = parent
        self.position = position

        self.g = 0
        self.h = 0
        self.f = 0

    def __eq__(self, other):
        return (self.position[0] == other.position[0] and self.position[1] == other.position[1])

def astar(maze, start, end):
    """Returns a list of tuples as a path from the given start to the given end in the given maze"""

    # Create start and end node
    start_node = Node(None, start)
    start_node.g = start_node.h = start_node.f = 0
    end_node = Node(None, end)
    end_node.g = end_node.h = end_node.f = 0

    # Initialize both open and closed list
    open_list = []
    closed_list = []

    # Add the start node
    open_list.append(start_node)

    # Loop until you find the end
    while len(open_list) > 0:
        # Get the current node
        # print([i.position for i in open_list])
        current_node = open_list[0]
        current_index = 0
        for index, item in enumerate(open_list):
            if item.f < current_node.f:
                current_node = item
                current_index = index

        # Pop current off open list, add to closed list
        open_list.pop(current_index)
        closed_list.append(current_node)

        # Found the goal
        if current_node == end_node:
            path = []
            current = current_node
            while current is not None:
                path.append(current.position)
                current = current.parent
            return path[::-1] # Return reversed path

        # Generate children
        children = []
        # st()
        for new_position in [(0, -1), (0, 1), (-1, 0), (1, 0)]: # Adjacent squares

            # Get node position
            node_position = (current_node.position[0] + new_position[0], current_node.position[1] + new_position[1])

            # Make sure within range
            if node_position[0] > (len(maze) - 1) or node_position[0] < 0 or node_position[1] > (len(maze[len(maze)-1]) -1) or node_position[1] < 0:
                continue

            # Make sure walkable terrain
            if maze[node_position[0]][node_position[1]] == '#':
                continue

            # Create new node
            new_node = Node(current_node, node_position)

            # Append
            children.append(new_node)

        # Loop through children
        # st()
        for child in children:

            # Child is on the closed list
            for closed_child in closed_list:
                if child == closed_child:
                    continue

            # Create the f, g, and h values
            child.g = current_node.g + 1
            child.h = ((child.position[0] - end_node.position[0]) ** 2) + ((child.position[1] - end_node.position[1]) ** 2)
            child.f = child.g + child.h

            # Child is already in the open list
            for open_node in open_list:
                if child == open_node and child.g > open_node.g:
                    continue

            # Add the child to the open list
            open_list.append(child)

In [ ]:
checkpoints = get_checkpoint_idxs(field)
combinations = get_all_combinations(checkpoints, 3)
combinations

[(array([0, 0]), array([1, 2]), array([2, 0])),
 (array([0, 0]), array([1, 2]), array([2, 4])),
 (array([0, 0]), array([2, 0]), array([2, 4])),
 (array([1, 2]), array([2, 0]), array([2, 4]))]

In [ ]:
grid = [list(i) for i in field]
grid

[['*', '#', '.', '.', '#'],
 ['.', '#', '*', '#', '.'],
 ['*', '.', '.', '.', '*']]

In [ ]:
combinations[0]

(array([0, 0]), array([1, 2]), array([2, 0]))

In [ ]:
get_all_combinations(np.array(combinations[0]), 2)

[(array([0, 0]), array([1, 2])),
 (array([0, 0]), array([2, 0])),
 (array([1, 2]), array([2, 0]))]

In [ ]:
distances = []
for each_comb in combinations:
    all_combinations = get_all_combinations(np.array(each_comb), 2)
    for i in range(len(all_combinations - 2)):
        start, end =all_combinations[i], all_combinations[i]

In [ ]:
[['*', '#', '.', '.', '#'],
 ['.', '#', '*', '#', '.'],
 ['*', '.', '.', '.', '*']]
astar(grid, [0, 0], [1, 2])

[[0, 0], (1, 0), (2, 0), (2, 1), (2, 2), (1, 2)]